### ISSUE TITLE
Crash in Wolvic 

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#1308]
## Configuration

Wolvic version: 1.6
Wolvic build ID: 308

Hardware: Quest 2

## Steps to Reproduce

1. No clear steps to reproduce the issue, but I got some while watching 360 videos in You Tube
2.
3.

## Current Behavior
Wolvic crashes 

## Expected Behavior
Wolvic shouldn't crash

## Error Logs and Stack Traces

<details open>

```
2024-03-13 14:39:47.872 18314-18314 VRB[CrashR...erService] com.igalia.wolvic.dev                D  onStartCommand
2024-03-13 14:39:47.907 18314-18387 AndroidRuntime          com.igalia.wolvic.dev                E  FATAL EXCEPTION: AsyncTask #1
                                                                                                    Process: com.igalia.wolvic.dev:crash, PID: 18314
                                                                                                    java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                                    	at android.os.AsyncTask$4.done(AsyncTask.java:415)
                                                                                                    	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                                                                                    	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)
                                                                                                    Caused by: java.lang.IllegalThreadStateException: Expected thread 2 ("main"), but running on thread 40 ("AsyncTask #1")
                                                                                                    	at org.mozilla.gecko.util.ThreadUtils.assertOnThreadComparison(ThreadUtils.java:127)
                                                                                                    	at org.mozilla.gecko.util.ThreadUtils.assertOnThread(ThreadUtils.java:93)
                                                                                                    	at org.mozilla.gecko.util.ThreadUtils.assertOnUiThread(ThreadUtils.java:84)
                                                                                                    	at org.mozilla.geckoview.GeckoRuntime.create(GeckoRuntime.java:570)
                                                                                                    	at com.igalia.wolvic.browser.api.impl.RuntimeImpl.<init>(RuntimeImpl.java:71)
                                                                                                    	at com.igalia.wolvic.browser.api.WFactory.createRuntime(WFactory.java:14)
                                                                                                    	at com.igalia.wolvic.browser.engine.EngineProvider.getOrCreateRuntime(EngineProvider.kt:72)
                                                                                                    	at com.igalia.wolvic.crashreporting.CrashReporterService.onHandleWork(CrashReporterService.java:66)
                                                                                                    	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
                                                                                                    	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
                                                                                                    	at android.os.AsyncTask$3.call(AsyncTask.java:394)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:920) 
```

</details>

**Comment by javifernandez** [comment]
I wasn't able to determine how to reproduce this crash; additionally, the backtrace is generated by the crashreport, so not very useful to determine the root cause. Closing it as INVALID for now.
