### ISSUE TITLE
[VisionGlass] Review proguard rules

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#1326]
We need to add proguard rules for the VisionGlass flavour as the minification process removes some important classes that make Wolvic crash when generating release packages.

**Comment by svillar** [comment]
For example this exception
```
03-22 17:44:57.991 27938 27938 W System.err: java.io.FileNotFoundException: 1080/port/up_char/palette.json: open failed: ENOENT (No such file or directory)
03-22 17:44:57.992 27938 27938 W System.err: 	at libcore.io.IoBridge.open(IoBridge.java:575)
03-22 17:44:57.992 27938 27938 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
03-22 17:44:57.992 27938 27938 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:115)
03-22 17:44:57.992 27938 27938 W System.err: 	at java.io.FileReader.<init>(FileReader.java:58)
03-22 17:44:57.992 27938 27938 W System.err: 	at com.baidu.rc.f0.b(Proguard:3)
03-22 17:44:57.992 27938 27938 W System.err: 	at com.baidu.rc.f0.<init>(Proguard:2)
03-22 17:44:57.992 27938 27938 W System.err: 	at com.baidu.rc.a0.s(Proguard:1)
03-22 17:44:57.993 27938 27938 W System.err: 	at com.baidu.rc.a0.a(Proguard:561)
03-22 17:44:57.993 27938 27938 W System.err: 	at com.baidu.rc.a0.p(Proguard:17)
03-22 17:44:57.993 27938 27938 W System.err: 	at com.baidu.rc.a0.c(Proguard:12)
03-22 17:44:57.993 27938 27938 W System.err: 	at com.baidu.rc.a0.j(Proguard:3)
03-22 17:44:57.993 27938 27938 W System.err: 	at com.baidu.rc.a0.n(Proguard:7)
03-22 17:44:57.993 27938 27938 W System.err: 	at com.baidu.i7.f.a(Proguard:43)
03-22 17:44:57.993 27938 27938 W System.err: 	at com.baidu.i7.f.t(Proguard:5)
03-22 17:44:57.993 27938 27938 W System.err: 	at com.baidu.i7.f.a(Proguard:7)
03-22 17:44:57.993 27938 27938 W System.err: 	at com.baidu.i7.g.run(Proguard:1)
03-22 17:44:57.993 27938 27990 I Bitmap  : source bitmap colorspace: sRGB IEC61966-2.1
03-22 17:44:57.993 27938 27938 W System.err: 	at com.baidu.jw.c.c(Proguard:3)
03-22 17:44:57.994 27938 27938 W System.err: 	at com.baidu.bh.a.a(Proguard:2)
03-22 17:44:57.994 27938 27938 W System.err: 	at com.baidu.bh.c.b(Proguard:1)
03-22 17:44:57.994 27938 27990 I Bitmap  : source bitmap colorspace: sRGB IEC61966-2.1
03-22 17:44:57.994 27938 27938 W System.err: 	at com.baidu.bh.c.f(Proguard:1)
03-22 17:44:57.994 27938 27938 W System.err: 	at com.baidu.i7.f.onStartInput(Proguard:8)
03-22 17:44:57.994 27938 27938 W System.err: 	at com.baidu.input.modular.ObservableImeService.onStartInputModule(Proguard:3)
03-22 17:44:57.994 27938 27990 I Bitmap  : source bitmap colorspace: sRGB IEC61966-2.1
03-22 17:44:57.994 27938 27938 W System.err: 	at com.baidu.input_huawei.ImeService.a(Proguard:49)
03-22 17:44:57.994 27938 27938 W System.err: 	at com.baidu.al.z.run(Proguard:1)
03-22 17:44:57.994 27938 27990 I Bitmap  : source bitmap colorspace: sRGB IEC61966-2.1
03-22 17:44:57.994 27938 27938 W System.err: 	at com.baidu.jw.c.c(Proguard:3)
03-22 17:44:57.994 27938 27990 I Bitmap  : source bitmap colorspace: sRGB IEC61966-2.1
03-22 17:44:57.995 27938 27938 W System.err: 	at com.baidu.bh.a.a(Proguard:2)
03-22 17:44:57.995 27938 27938 W System.err: 	at com.baidu.bh.c.b(Proguard:1)
03-22 17:44:57.995 27938 27938 W System.err: 	at com.baidu.bh.c.d(Proguard:1)
03-22 17:44:57.995 27938 27990 I Bitmap  : source bitmap colorspace: sRGB IEC61966-2.1
03-22 17:44:57.995 27938 27938 W System.err: 	at com.baidu.input_huawei.ImeService.onStartInput(Proguard:1)
03-22 17:44:57.995 27938 27938 W System.err: 	at android.inputmethodservice.InputMethodService.doStartInput(InputMethodService.java:2793)
03-22 17:44:57.995 27938 27938 W System.err: 	at android.inputmethodservice.InputMethodService$InputMethodImpl.startInput(InputMethodService.java:833)
03-22 17:44:57.995 27938 27990 I Bitmap  : source bitmap colorspace: sRGB IEC61966-2.1
03-22 17:44:57.995 27938 27938 W System.err: 	at android.inputmethodservice.InputMethodService$InputMethodImpl.dispatchStartInputWithToken(InputMethodService.java:863)
03-22 17:44:57.995 27938 27938 W System.err: 	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:199)
```

**Comment by svillar** [comment]
It was not caused by proguard rules in the end. Closing.
