### ISSUE TITLE
Java exception in CrashReporterService

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#139]
## Configuration

Wolvic version: 0.9.6

Hardware:  Oculus Quest 2

## Steps to Reproduce

It's difficult to reproduce, it happens sometimes after mixing local builds and installations from the Oculus Store

## Current Behavior
Wolvic crashes at startup

## Expected Behavior
No crash :smile: 

## Error Logs and Stack Traces
This is the stack trace
```
05-25 17:11:56.277 13248 13269 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
05-25 17:11:56.277 13248 13269 E AndroidRuntime: Process: com.igalia.wolvic:crash, PID: 13248
05-25 17:11:56.277 13248 13269 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-25 17:11:56.277 13248 13269 E AndroidRuntime:        at android.os.AsyncTask$4.done(AsyncTask.java:399)
05-25 17:11:56.277 13248 13269 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
05-25 17:11:56.277 13248 13269 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
05-25 17:11:56.277 13248 13269 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
05-25 17:11:56.277 13248 13269 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-25 17:11:56.277 13248 13269 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-25 17:11:56.277 13248 13269 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:919)
05-25 17:11:56.277 13248 13269 E AndroidRuntime: Caused by: java.lang.IllegalThreadStateException: Expected thread 2 ("main"), but running on thread 573 ("AsyncTask #1")
05-25 17:11:56.277 13248 13269 E AndroidRuntime:        at org.mozilla.gecko.util.ThreadUtils.assertOnThread(ThreadUtils.java:7)
05-25 17:11:56.277 13248 13269 E AndroidRuntime:        at org.mozilla.gecko.util.ThreadUtils.assertOnUiThread(ThreadUtils.java:2)
05-25 17:11:56.277 13248 13269 E AndroidRuntime:        at org.mozilla.geckoview.GeckoRuntime.create(GeckoRuntime.java:3)
05-25 17:11:56.277 13248 13269 E AndroidRuntime:        at com.igalia.wolvic.browser.api.impl.RuntimeImpl.<init>(RuntimeImpl.java:31)
05-25 17:11:56.277 13248 13269 E AndroidRuntime:        at com.igalia.wolvic.browser.api.WFactory.createRuntime(WFactory.java:1)
05-25 17:11:56.277 13248 13269 E AndroidRuntime:        at com.igalia.wolvic.browser.engine.EngineProvider.getOrCreateRuntime(EngineProvider.kt:29)
05-25 17:11:56.277 13248 13269 E AndroidRuntime:        at com.igalia.wolvic.crashreporting.CrashReporterService.onHandleWork(CrashReporterService.java:2)
05-25 17:11:56.277 13248 13269 E AndroidRuntime:        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:17)
05-25 17:11:56.277 13248 13269 E AndroidRuntime:        at android.os.AsyncTask$3.call(AsyncTask.java:378)
05-25 17:11:56.277 13248 13269 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

```
```

</details>

**Comment by svillar** [comment]
Uploaded PR #140 that fixes this issue

**Comment by svillar** [comment]
This has been already merged
