### ISSUE TITLE
Crash when handling onSlowScript event

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#152]
## Configuration

Wolvic version: 0.9.6
Wolvic build ID: 33

Hardware: Oculus Quest2

## Steps to Reproduce
Similar to issue #65, it requires some extensions to be enabled at the same time.

## Current Behavior
Wolvic crashes

## Expected Behavior
Wolvic should not crash

## Error Logs and Stack Traces

<details open>

```
```
06-22 11:54:01.501  7417  7417 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'org.mozilla.geckoview.GeckoResult org.mozilla.geckoview.GeckoResult.map(org.mozilla.geckoview.GeckoResult$OnValueMapper)' on a null object reference
06-22 11:54:01.501  7417  7417 E AndroidRuntime: 	at com.igalia.wolvic.browser.api.impl.ContentDelegateImpl.onSlowScript(ContentDelegateImpl.java:1)
06-22 11:54:01.501  7417  7417 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession$4.handleMessage(GeckoSession.java:4)
06-22 11:54:01.501  7417  7417 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession$4.handleMessage(GeckoSession.java:1)
06-22 11:54:01.501  7417  7417 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:2)
06-22 11:54:01.501  7417  7417 E AndroidRuntime: 	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:2)
06-22 11:54:01.501  7417  7417 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
06-22 11:54:01.501  7417  7417 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-22 11:54:01.501  7417  7417 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
06-22 11:54:01.501  7417  7417 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7391)
06-22 11:54:01.501  7417  7417 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-22 11:54:01.501  7417  7417 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
06-22 11:54:01.501  7417  7417 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
```

</details>

**Comment by svillar** [comment]
Will be fixed by PR #153
