### ISSUE TITLE
[Meta] No web contents when adding new windows in v72

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#1638]
Steps to reproduce
1. Click on "+" to add a new window

Observed behaviour:
* the new window does not have web contents
* it is not possible to interact with the previous window
* things go back to life when closing the newly added window

This started happening in Beta version of MetaOS v72.

**Comment by svillar** [comment]
I think I found the reason, it's this unhandled exception
```
 System.err            W  java.lang.IllegalStateException: Compositor must be ready before pixels can be captured
                       W  	at org.mozilla.geckoview.GeckoDisplay$ScreenshotBuilder.capture(GeckoDisplay.java:463)
                       W  	at com.igalia.wolvic.browser.api.impl.DisplayImpl.capturePixelsWithAspectPreservingSize(DisplayImpl.java:49)
                       W  	at com.igalia.wolvic.browser.engine.Session.captureBitmap(Session.java:639)
                       W  	at com.igalia.wolvic.ui.widgets.WindowWidget.captureImage(WindowWidget.java:1953)
                       W  	at com.igalia.wolvic.ui.widgets.WindowWidget.onPageStop(WindowWidget.java:1938)
                       W  	at com.igalia.wolvic.browser.engine.Session.onPageStop(Session.java:1275)
                       W  	at com.igalia.wolvic.browser.api.impl.ProgressDelegateImpl.onPageStop(ProgressDelegateImpl.java:26)
                       W  	at org.mozilla.geckoview.GeckoSession$8.handleMessage(GeckoSession.java:1006)
                       W  	at org.mozilla.geckoview.GeckoSession$8.handleMessage(GeckoSession.java:992)
                       W  	at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:88)
                       W  	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:426)
                       W  	at android.os.Handler.handleCallback(Handler.java:938)
                       W  	at android.os.Handler.dispatchMessage(Handler.java:99)
                       W  	at android.os.Looper.loopOnce(Looper.java:214)
                       W  	at android.os.Looper.loop(Looper.java:304)
                       W  	at android.app.ActivityThread.main(ActivityThread.java:7918)
                       W  	at java.lang.reflect.Method.invoke(Native Method)
                       W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                       W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1010)
```
