### ISSUE TITLE
Crash at statup

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#1648]
## Configuration

Wolvic version:  1.7.8
Wolvic build ID: 

Hardware:  Quest2 (v72)

## Steps to Reproduce

1. Launch Wolvic
2.
3.

## Current Behavior

Wolvic crashes at startup

## Expected Behavior

Wolci shouldn't crash and starts up normally.

## Error Logs and Stack Traces

<details open>

```
25217-25217 VRB[WindowWidget]        D  onCurrentSessionChange: 28064834
25217-25217 VRB[WindowWidget]        D  surfaceChanged: 154593643
25217-25217 AndroidRuntime           D  Shutting down VM
25217-25217 AndroidRuntime           E  FATAL EXCEPTION: main (Ask Gemini)
                                        Process: com.igalia.wolvic.dev, PID: 25217
                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.igalia.wolvic.dev/com.igalia.wolvic.VRBrowserActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.igalia.wolvic.ui.widgets.Windows$ContentType.ordinal()' on a null object reference
                                        	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3724)
                                        	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3881)
                                        	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                        	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                        	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                        	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2270)
                                        	at android.os.Handler.dispatchMessage(Handler.java:106)
                                        	at android.os.Looper.loopOnce(Looper.java:214)
                                        	at android.os.Looper.loop(Looper.java:304)
                                        	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                        	at java.lang.reflect.Method.invoke(Native Method)
                                        	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                        	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1010)
                                        Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.igalia.wolvic.ui.widgets.Windows$ContentType.ordinal()' on a null object reference
                                        	at com.igalia.wolvic.ui.widgets.Windows.addRestoredWindow(Windows.java:374)
                                        	at com.igalia.wolvic.ui.widgets.Windows.restoreWindows(Windows.java:804)
                                        	at com.igalia.wolvic.ui.widgets.Windows.<init>(Windows.java:230)
                                        	at com.igalia.wolvic.VRBrowserActivity.initializeWidgets(VRBrowserActivity.java:414)
                                        	at com.igalia.wolvic.VRBrowserActivity.onCreate(VRBrowserActivity.java:357)
                                        	at android.app.Activity.performCreate(Activity.java:8068)
                                        	at android.app.Activity.performCreate(Activity.java:8048)
                                        	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
                                        	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3705)
                                        	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3881) 
                                        	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
                                        	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                        	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                        	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2270) 
                                        	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                        	at android.os.Looper.loopOnce(Looper.java:214) 
                                        	at android.os.Looper.loop(Looper.java:304) 
                                        	at android.app.ActivityThread.main(ActivityThread.java:7918) 
                                        	at java.lang.reflect.Method.invoke(Native Method) 
                                        	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                        	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1010) 
25217-25217 GeckoCrashHandler        E  >>> REPORTING UNCAUGHT EXCEPTION FROM THREAD 2 ("main") (Ask Gemini)
                                        java.lang.NullPointerException: Attempt to invoke virtual method 'int com.igalia.wolvic.ui.widgets.Windows$ContentType.ordinal()' on a null object reference
                                        	at com.igalia.wolvic.ui.widgets.Windows.addRestoredWindow(Windows.java:374)
                                        	at com.igalia.wolvic.ui.widgets.Windows.restoreWindows(Windows.java:804)
                                        	at com.igalia.wolvic.ui.widgets.Windows.<init>(Windows.java:230)
                                        	at com.igalia.wolvic.VRBrowserActivity.initializeWidgets(VRBrowserActivity.java:414)
                                        	at com.igalia.wolvic.VRBrowserActivity.onCreate(VRBrowserActivity.java:357)
                                        	at android.app.Activity.performCreate(Activity.java:8068)
                                        	at android.app.Activity.performCreate(Activity.java:8048)
                                        	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
                                        	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3705)
                                        	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3881)
                                        	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                        	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                        	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                        	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2270)
                                        	at android.os.Handler.dispatchMessage(Handler.java:106)
                                        	at android.os.Looper.loopOnce(Looper.java:214)
                                        	at android.os.Looper.loop(Looper.java:304)
                                        	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                        	at java.lang.reflect.Method.invoke(Native Method)
                                        	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                        	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1010)


```

</details>

**Comment by svillar** [comment]
@javifernandez are you sure you don't have local changes?

The line triggering the null pointer exception is `newWindow.getSession().loadUri(UrlUtils.ABOUT_HISTORY` and is inside a block that checks that `newWindow.getSession() != null`

**Comment by svillar** [comment]
> @javifernandez are you sure you don't have local changes?
> 
> The line triggering the null pointer exception is `newWindow.getSession().loadUri(UrlUtils.ABOUT_HISTORY` and is inside a block that checks that `newWindow.getSession() != null`

I was not using main. After checking out main, it looks like the null object is aState which is tagged as @NonNull. There is just one caller which is `restoreWindows()` which basically traverses the `mWindowsState.regularWindow` array. That array only gets newly created window states so I cannot see how that could be null.

**Comment by svillar** [comment]
Tagging as low prio as it was only reproduced once.

**Comment by svillar** [comment]
After some debugging I found that this was caused by https://github.com/Igalia/wolvic/pull/1644

In that PR the panelType attribute of WindowState class changed its type from int to ContentType enum. The problem is that enums in Java are classes not integers. Then when restoring a session created before that patch landed, the code is expecting a serialized class but in the saved window state there is just an integer. If that integer is 0 then it's interpreted as a null class which must never happen. That's why then it later crashes.
