### ISSUE TITLE
App crashes when launching on Android 12

### ISSUE THREAD

**Issue by otsenreDC** [Igalia/wolvic#357]
## Configuration

Wolvic version: 1.2
Wolvic build ID: 52
Comit hash: f497f43fd904eed4e3f93eeb2960bbf078b78f42

Hardware: N/A
Emulator: Android 12.0 x86_64

Extras
Android Studio: Dolphin | 2021.3.1 Patch 1

## Steps to Reproduce

1. Clone the project
2. Build the project
3. Install the application in an emulator running Android 12
4. Launch the application

## Current Behavior
The application crashes right after launching.

## Expected Behavior
The application is launched.

## Possible Solution
The problem seems to be related to the PendingIntent requiring one of the INMUTABLE_FLAG or MUTABLE_FLAG. Although the problem was solved in [PR #301](https://github.com/Igalia/wolvic/pull/301), in my research the WorkerManager might be conflicting as read [here](https://developer.android.com/jetpack/androidx/releases/work#2.7.0-alpha03).

> Make PendingIntent mutability explicit, to fix a crash when targeting Android 12. ([b/180884673](https://issuetracker.google.com/issues/180884673))

But upgrading the library to 2.7.0, 2.7.1 or 2.8.0 do not solve the error I'm facing.

## Error Logs and Stack Traces
```
---------------------------- PROCESS STARTED (13067) for package com.igalia.wolvic ----------------------------
2022-11-23 10:04:44.928 13067-13067 GraphicsEnvironment     com.igalia.wolvic                    V  ANGLE Developer option for 'com.igalia.wolvic' set to: 'default'
2022-11-23 10:04:44.928 13067-13067 GraphicsEnvironment     com.igalia.wolvic                    V  Neither updatable production driver nor prerelease driver is supported.
2022-11-23 10:04:44.932 13067-13067 NetworkSecurityConfig   com.igalia.wolvic                    D  No Network Security Config specified, using platform default
2022-11-23 10:04:44.932 13067-13067 NetworkSecurityConfig   com.igalia.wolvic                    D  No Network Security Config specified, using platform default
2022-11-23 10:04:44.983 13067-13096 libEGL                  com.igalia.wolvic                    D  loaded /vendor/lib64/egl/libEGL_emulation.so
2022-11-23 10:04:44.988 13067-13096 libEGL                  com.igalia.wolvic                    D  loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
2022-11-23 10:04:44.994 13067-13093 Compatibil...geReporter com.igalia.wolvic                    D  Compat change id reported: 160794467; UID 10148; state: ENABLED
2022-11-23 10:04:44.996 13067-13096 libEGL                  com.igalia.wolvic                    D  loaded /vendor/lib64/egl/libGLESv2_emulation.so
2022-11-23 10:04:44.998 13067-13093 AndroidRuntime          com.igalia.wolvic                    E  FATAL EXCEPTION: pool-3-thread-1
                                                                                                    Process: com.igalia.wolvic, PID: 13067
                                                                                                    java.lang.IllegalArgumentException: com.igalia.wolvic: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                                    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
                                                                                                    	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
                                                                                                    	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
                                                                                                    	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
                                                                                                    	at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:196)
                                                                                                    	at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:128)
                                                                                                    	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:93)
                                                                                                    	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)
2022-11-23 10:04:45.025 13067-13093 Process                 com.igalia.wolvic                    I  Sending signal. PID: 13067 SIG: 9
---------------------------- PROCESS ENDED (13067) for package com.igalia.wolvic ----------------------------
```
<details open>

```
```

</details>

**Comment by svillar** [comment]
Just to be clear, this only happens in the emulator right? We indeed fixed that when HVR devices migrated to Android 12, and we haven't got any crash report since that.

**Comment by svillar** [comment]
BTW did you check whether this suggestion
> Set to targetSdkVersion to Android R (and leave the compile sdk set to S). This should work around the issue with PendingIntent mutability.

does the trick?

**Comment by otsenreDC** [comment]
Setting the targetSdk to Android 30 definitely worked. 

About the hardware. We are using a devive based on the Snapdraon XR2, we are getting a new device running Android 12 and I started testing Wolvic with the emulator. That been said, I cannot confirm is something that only happens in the Emulator.
