### ISSUE TITLE
Crash when playing webpage video with audio

### ISSUE THREAD

**Issue by xuqiqiang** [Igalia/wolvic#732]
## Configuration

Wolvic version: Latest Main branch
Wolvic build ID: Latest Main branch

Hardware: Snapdragon Spaces XR Device, Android version: 12

## Steps to Reproduce

1.Select the spaces build variant
2.run it on the Snapdragon Spaces XR Device
3.Visit some webpage which contains video with audio

## Current Behavior

Crash when playing webpage video with audio:

06-16 13:51:21.982 22860 22925 I CCodec  : Created component [c2.android.avc.decoder]
06-16 13:51:21.985 22860 22925 D ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.max-count.values
06-16 13:51:21.985 22860 22925 D ReflectedParamUpdater: extent() != 1 for single value type: output.subscribed-indices.values
06-16 13:51:21.985 22860 22925 D ReflectedParamUpdater: extent() != 1 for single value type: input.buffers.allocator-ids.values
06-16 13:51:21.986 22860 22925 D ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.allocator-ids.values
06-16 13:51:21.986 22860 22925 D ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.allocator-ids.values
06-16 13:51:21.986 22860 22925 D ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.pool-ids.values
06-16 13:51:21.986 22860 22925 D ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.pool-ids.values
06-16 13:51:21.987 22860 22925 D ReflectedParamUpdater: ignored struct field coded.color-format.locations
06-16 13:51:21.987 22860 22925 D ReflectedParamUpdater: ignored struct field raw.hdr-static-info.mastering
06-16 13:51:21.988 22860 22925 I CCodecConfig: query failed after returning 12 values (BAD_INDEX)
06-16 13:51:21.989 22860 22925 W ColorUtils: expected specified color aspects (2:0:0:0)
06-16 13:51:21.989 22860 22924 I MediaCodec: MediaCodec will operate in async mode
06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: codec creation error
06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: android.media.MediaCodec$CodecException: Error 0xffffffe0
06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: 	at android.media.MediaCodec.native_configure(Native Method)
06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: 	at android.media.MediaCodec.configure(MediaCodec.java:2176)
06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: 	at android.media.MediaCodec.configure(MediaCodec.java:2092)
06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: 	at org.mozilla.gecko.media.LollipopAsyncCodec.configure(LollipopAsyncCodec.java:154)
06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: 	at org.mozilla.gecko.media.Codec.configureCodec(Codec.java:519)
06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: 	at org.mozilla.gecko.media.Codec.configure(Codec.java:423)
06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: 	at org.mozilla.gecko.media.ICodec$Stub.onTransact(ICodec.java:137)
06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: 	at android.os.Binder.execTransact(Binder.java:1143)
06-16 13:51:21.995 22860 22878 W GeckoRemoteCodec: unable to configure c2.android.avc.decoder. Try next.
06-16 13:51:21.997  1288  4122 W ResourceManagerService: reclaimResourcesFromClientsPendingRemoval called with untrusted pid 22413, using calling pid 22860
06-16 13:51:21.999     0     0 I binder  : release 22413:22857 transaction 3583946 out, still active
06-16 13:51:21.999     0     0 I binder  : undelivered TRANSACTION_COMPLETE
06-16 13:51:21.999     0     0 I binder  : undelivered transaction 3584145, process died.
06-16 13:51:21.999     0     0 I binder  : undelivered transaction 3584149, process died.
06-16 13:51:21.999     0     0 I binder  : undelivered transaction 3584142, process died.
06-16 13:51:21.999  1531  6814 I ActivityManager: Process com.igalia.wolvic:tab23 (pid 22413) has died: fg  SVC 
06-16 13:51:21.999  1531  1790 I libprocessgroup: Successfully killed process cgroup uid 10120 pid 22413 in 0ms
06-16 13:51:22.000 22860 22877 E GeckoRemoteCodec: Callbacks is dead
06-16 13:51:22.002 22860 22860 I GeckoMediaManager: Media service has been unbound. Stopping.
06-16 13:51:22.004 22860 22903 I hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
06-16 13:51:22.004 22860 22930 I CCodec  : setting up 'default' as default (vendor) store
06-16 13:51:22.006 22860 22930 I CCodec  : Created component [c2.android.avc.decoder]
06-16 13:51:22.013 22860 22860 W GeckoMediaManager: unbound while client still active.
06-16 13:51:22.013 22860 22860 I Process : Sending signal. PID: 22860 SIG: 9

## Expected Behavior

It should work normally.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Could you please provide more information about the device and the site you're visiting?

Note that from the traces it looks like your system does not provide the required codecs
```
06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: codec creation error
06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: android.media.MediaCodec$CodecException: Error 0xffffffe0
06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: at android.media.MediaCodec.native_configure(Native Method)
06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: at android.media.MediaCodec.configure(MediaCodec.java:2176)
06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: at android.media.MediaCodec.configure(MediaCodec.java:2092)
06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: at org.mozilla.gecko.media.LollipopAsyncCodec.configure(LollipopAsyncCodec.java:154)
```

**Comment by xuqiqiang** [comment]
> Could you please provide more information about the device and the site you're visiting?
> 
> Note that from the traces it looks like your system does not provide the required codecs
> 
> ```
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: codec creation error
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: android.media.MediaCodec$CodecException: Error 0xffffffe0
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: at android.media.MediaCodec.native_configure(Native Method)
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: at android.media.MediaCodec.configure(MediaCodec.java:2176)
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: at android.media.MediaCodec.configure(MediaCodec.java:2092)
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: at org.mozilla.gecko.media.LollipopAsyncCodec.configure(LollipopAsyncCodec.java:154)
> ```

All web videos with audio will crash, for example:

https://m.baidu.com/video/page?pd=video_page&nid=6980293158143497100&sign=15857016361955049381&word=ff&oword=ff&atn=index&frsrcid=48305&ext=%7B%22jsy%22%3A1%7D&top=%7B%22sfhs%22%3A1%2C%22_hold%22%3A2%7D&_t=1686907480481

But it work well when playing without audio.

**Comment by xuqiqiang** [comment]
> Could you please provide more information about the device and the site you're visiting?
> 
> Note that from the traces it looks like your system does not provide the required codecs
> 
> ```
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: codec creation error
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: android.media.MediaCodec$CodecException: Error 0xffffffe0
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: at android.media.MediaCodec.native_configure(Native Method)
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: at android.media.MediaCodec.configure(MediaCodec.java:2176)
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: at android.media.MediaCodec.configure(MediaCodec.java:2092)
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: at org.mozilla.gecko.media.LollipopAsyncCodec.configure(LollipopAsyncCodec.java:154)
> ```

Sometime the crash log is like this:

2023-06-16 15:43:19.344 11731-12134/com.igalia.wolvic I/AAudio: AAudioStreamBuilder_openStream() called ----------------------------------------
2023-06-16 15:43:19.344 11731-12134/com.igalia.wolvic I/AudioStreamBuilder: rate   =  44100, channels  = 2, channelMask = 0x80000003, format   = 1, sharing = SH, dir = OUTPUT
2023-06-16 15:43:19.344 11731-12134/com.igalia.wolvic I/AudioStreamBuilder: device =      0, sessionId = -1, perfMode = 11, callback: ON with frames = 0
2023-06-16 15:43:19.344 11731-12134/com.igalia.wolvic I/AudioStreamBuilder: usage  =      1, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0
2023-06-16 15:43:19.344 11731-12134/com.igalia.wolvic I/AudioStreamBuilder: privacy sensitive = false
2023-06-16 15:43:19.344 11731-12134/com.igalia.wolvic I/AudioStreamBuilder: opPackageName = (null)
2023-06-16 15:43:19.344 11731-12134/com.igalia.wolvic I/AudioStreamBuilder: attributionTag = (null)
2023-06-16 15:43:19.344 11731-12134/com.igalia.wolvic D/AudioStreamBuilder: build() MMAP not used because AAUDIO_PERFORMANCE_MODE_LOW_LATENCY not requested.
2023-06-16 15:43:19.344 11731-12134/com.igalia.wolvic D/ia.wolvic:tab3: PlayerBase::PlayerBase()
2023-06-16 15:43:19.344 11731-12134/com.igalia.wolvic D/AudioStreamTrack: open(), request notificationFrames = 0, frameCount = 4410
2023-06-16 15:43:19.355 11731-12134/com.igalia.wolvic D/AAudioStream: setState(s#1) from 0 to 2
2023-06-16 15:43:19.356 11731-12134/com.igalia.wolvic I/AAudio: AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#1 ----------------
2023-06-16 15:43:19.356 11731-12134/com.igalia.wolvic D/AAudio: AAudioStream_requestStart(s#1) called --------------
2023-06-16 15:43:19.356 11731-12134/com.igalia.wolvic D/AAudioStream: setState(s#1) from 2 to 3
2023-06-16 15:43:19.362 11731-11761/com.igalia.wolvic D/AudioStreamLegacy: onAudioDeviceUpdate(deviceId = 3)
2023-06-16 15:43:19.363 11731-12134/com.igalia.wolvic D/AAudio: AAudioStream_requestStart(s#1) returned 0 ---------
2023-06-16 15:43:19.363 11731-12134/com.igalia.wolvic I/Gecko: [Child 11731, Unnamed thread 7340979560] WARNING: 7340979670 Could not set cubeb stream name.: file /builds/worker/checkouts/gecko/dom/media/AudioStream.cpp:321
2023-06-16 15:43:19.395 11731-12217/com.igalia.wolvic D/AAudioStream: setState(s#1) from 3 to 4
2023-06-16 15:43:19.413 11731-11868/com.igalia.wolvic I/Gecko: Exiting due to channel error.
2023-06-16 15:43:19.414 11889-11916/com.igalia.wolvic I/Gecko: Exiting due to channel error.
2023-06-16 15:43:19.530 12139-12183/com.igalia.wolvic E/GeckoRemoteCodec: Callbacks is dead
2023-06-16 15:43:19.530 12139-12173/com.igalia.wolvic E/GeckoRemoteCodec: Callbacks is dead
2023-06-16 15:43:19.532 12139-12184/com.igalia.wolvic I/hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
2023-06-16 15:43:19.533 12139-12187/com.igalia.wolvic E/ia.wolvic:medi: getConsumerUsage failed to transact: -32
2023-06-16 15:43:19.533 12139-12187/com.igalia.wolvic E/ia.wolvic:medi: getUniqueId failed to transact: -32
2023-06-16 15:43:19.533 12139-12187/com.igalia.wolvic D/SurfaceUtils: connecting to surface 0x74d974a4c0, reason connectToSurface
2023-06-16 15:43:19.533 12139-12187/com.igalia.wolvic I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 12430339
2023-06-16 15:43:19.533 12139-12187/com.igalia.wolvic D/SurfaceUtils: disconnecting from surface 0x74d974a4c0, reason connectToSurface(reconnect)
2023-06-16 15:43:19.533 12139-12187/com.igalia.wolvic D/SurfaceUtils: connecting to surface 0x74d974a4c0, reason connectToSurface(reconnect)
2023-06-16 15:43:19.536 12139-12139/com.igalia.wolvic I/GeckoMediaManager: Media service has been unbound. Stopping.
2023-06-16 15:43:19.537 12139-12188/com.igalia.wolvic D/SurfaceUtils: set up nativeWindow 0x74d974a4c0 for 1280x720, color 0x7fa30c06, rotation 0, usage 0x20402900
2023-06-16 15:43:19.537 12139-12187/com.igalia.wolvic D/SurfaceUtils: disconnecting from surface 0x74d97460a0, reason disconnectFromSurface
2023-06-16 15:43:19.537 12139-12187/com.igalia.wolvic E/Surface: freeAllBuffers: 9 buffers were freed while being dequeued!
2023-06-16 15:43:19.537 12139-12139/com.igalia.wolvic W/GeckoMediaManager: unbound while client still active.
2023-06-16 15:43:19.537 12139-12187/com.igalia.wolvic E/SurfaceUtils: Failed to disconnect from surface 0x74d97460a0, err -32
2023-06-16 15:43:19.537 12139-12187/com.igalia.wolvic W/MediaCodec: nativeWindowDisconnect returned an error: Broken pipe (-32)
2023-06-16 15:43:19.537 12139-12139/com.igalia.wolvic I/Process: Sending signal. PID: 12139 SIG: 9

**Comment by xuqiqiang** [comment]
> Could you please provide more information about the device and the site you're visiting?
> 
> Note that from the traces it looks like your system does not provide the required codecs
> 
> ```
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: codec creation error
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: android.media.MediaCodec$CodecException: Error 0xffffffe0
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: at android.media.MediaCodec.native_configure(Native Method)
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: at android.media.MediaCodec.configure(MediaCodec.java:2176)
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: at android.media.MediaCodec.configure(MediaCodec.java:2092)
> 06-16 13:51:21.995 22860 22878 E GeckoRemoteCodec: at org.mozilla.gecko.media.LollipopAsyncCodec.configure(LollipopAsyncCodec.java:154)
> ```

There is no such problem when our XR device run [FirefoxReality](https://github.com/MozillaReality/FirefoxReality).
May I ask if there is any difference.

**Comment by svillar** [comment]
I have just tried the link you shared with a Lenovo VRX (SnapdragonSpaces) and it works perfectly no crash.

There are multiple differences with FirefoxReality, but the important one here is that we're using a much more recent version of Gecko that might have introduced some bug in your platform.

**Comment by xuqiqiang** [comment]
Can you help us adapt it for our device please? We can send our SnapdragonSpaces XR Device over to you.

**Comment by svillar** [comment]
Closing as this is an unsupported device.
