### ISSUE TITLE
Saved logins disappeared after upgrading from 1.4.2 to 1.5 

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#987]
## Configuration

Wolvic version:  1.5 
Wolvic build ID:  112

Hardware:  Oculus Quest2

## Steps to Reproduce

1.  Before upgrading, ensure you have Wolvic 1.4.2
2. Go to Settings > Privacy and Security > Logins and Passwords > Saved Logins
3. Verify there are a few saved logins
4. Quit the app 
5. Upgrade to 1.5
6. Go to Settings > Privacy and Security > Logins and Passwords > Saved Logins

## Current Behavior

The list of saved logins is the same we had 1.4.2

## Expected Behavior

The list of saved logins is empty

## Context

The version 1.5 ships a major upgrade of the Mozilla components (from 104 to 116) which is probably causing this bug in the db upgrading procedures.

Although the old saved login are missing, Wolvic can save new logins on the storage db. 

## Error Logs and Stack Traces

<details open>

In the first phases of the startup, Wolvic runs the Places API initialization:

```
2023-09-19 23:39:42.850 15171-15287 places                  com.igalia.wolvic.metastore          D  places_cac2_places_api_new
2023-09-19 23:39:42.850 15171-15287 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: opening database
2023-09-19 23:39:42.850 15171-15287 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: checking if initialization is necessary
2023-09-19 23:39:42.853 15171-15287 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: preparing
2023-09-19 23:39:42.853 15171-15287 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: upgrading database to 14
2023-09-19 23:39:42.853 15171-15287 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 13 to 17
2023-09-19 23:39:42.853 15171-15287 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 13 to 13
2023-09-19 23:39:42.853 15171-15287 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: upgrading database to 15
2023-09-19 23:39:42.854 15171-15287 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 14 to 17
2023-09-19 23:39:42.854 15171-15287 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 14 to 14
```

Later on, there is an unexpected assertion trying to read the Bookmarks store db:

```
2023-09-19 23:39:42.867 15171-15214 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: upgrading database to 15
2023-09-19 23:39:42.867 15171-15214 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 14 to 17
2023-09-19 23:39:42.867 15171-15214 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 14 to 14
2023-09-19 23:39:42.868 15171-15214 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: upgrading database to 16
2023-09-19 23:39:42.868 15171-15214 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 15 to 17
2023-09-19 23:39:42.869 15171-15214 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: upgrading database to 17
2023-09-19 23:39:42.869 15171-15214 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 16 to 17
2023-09-19 23:39:42.869 15171-15287 PlacesBookmarksStorage  com.igalia.wolvic.metastore          W  Ignoring PlacesApiException while running getTree
                                                                                                    mozilla.appservices.places.uniffi.PlacesApiException$UnexpectedPlacesException: reason=Error opening database: Error executing SQL: duplicate column name: unknown_fields
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.read(places.kt:21)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.read(places.kt:1)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverter$DefaultImpls.liftFromRustBuffer(places.kt:13)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterRustBuffer$DefaultImpls.liftFromRustBuffer(places.kt:6)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.liftFromRustBuffer(places.kt:2)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.liftFromRustBuffer(places.kt:1)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterRustBuffer$DefaultImpls.lift(places.kt:7)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.lift(places.kt:3)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.lift(places.kt:2)
                                                                                                    	at mozilla.appservices.places.uniffi.PlacesApiException$ErrorHandler.lift(places.kt:2)
                                                                                                    	at mozilla.appservices.places.uniffi.PlacesApiException$ErrorHandler.lift(places.kt:1)
                                                                                                    	at mozilla.appservices.places.uniffi.PlacesKt.placesApiNew(places.kt:107)
                                                                                                    	at mozilla.appservices.places.PlacesApi.<init>(PlacesConnection.kt:9)
                                                                                                    	at mozilla.components.browser.storage.sync.RustPlacesConnection.init(Connection.kt:29)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:15)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesStorage.getPlaces$browser_storage_sync_release(PlacesStorage.kt:3)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesStorage$reader$2.invoke(PlacesStorage.kt:3)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesStorage.getReader$browser_storage_sync_release(PlacesStorage.kt:3)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$getTree$2.invokeSuspend(PlacesBookmarksStorage.kt:12)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:124)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
```

And after this, another unhandled exception trying to access the History storage db:

```
2023-09-19 23:39:42.871 15171-15214 PlacesHistoryStorage    com.igalia.wolvic.metastore          W  Ignoring PlacesApiException while running getDetailedVisits
                                                                                                    mozilla.appservices.places.uniffi.PlacesApiException$UnexpectedPlacesException: reason=Error opening database: Error executing SQL: duplicate column name: unknown_fields
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.read(places.kt:21)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.read(places.kt:1)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverter$DefaultImpls.liftFromRustBuffer(places.kt:13)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterRustBuffer$DefaultImpls.liftFromRustBuffer(places.kt:6)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.liftFromRustBuffer(places.kt:2)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.liftFromRustBuffer(places.kt:1)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterRustBuffer$DefaultImpls.lift(places.kt:7)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.lift(places.kt:3)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.lift(places.kt:2)
                                                                                                    	at mozilla.appservices.places.uniffi.PlacesApiException$ErrorHandler.lift(places.kt:2)
                                                                                                    	at mozilla.appservices.places.uniffi.PlacesApiException$ErrorHandler.lift(places.kt:1)
                                                                                                    	at mozilla.appservices.places.uniffi.PlacesKt.placesApiNew(places.kt:107)
                                                                                                    	at mozilla.appservices.places.PlacesApi.<init>(PlacesConnection.kt:9)
                                                                                                    	at mozilla.components.browser.storage.sync.RustPlacesConnection.init(Connection.kt:29)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:15)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesStorage.getPlaces$browser_storage_sync_release(PlacesStorage.kt:3)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesHistoryStorage$getDetailedVisits$2.invokeSuspend(PlacesHistoryStorage.kt:19)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:124)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
```

Continuing with the startup, another unexpected exception with the same likely root cause:

```
2023-09-19 23:39:42.974 15171-15214 places                  com.igalia.wolvic.metastore          D  places_cac2_places_api_new
2023-09-19 23:39:42.974 15171-15214 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: opening database
2023-09-19 23:39:42.974 15171-15214 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: checking if initialization is necessary
2023-09-19 23:39:42.976 15171-15214 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: preparing
2023-09-19 23:39:42.977 15171-15214 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: upgrading database to 14
2023-09-19 23:39:42.977 15171-15214 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 13 to 17
2023-09-19 23:39:42.977 15171-15214 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 13 to 13
2023-09-19 23:39:42.977 15171-15214 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: upgrading database to 15
2023-09-19 23:39:42.977 15171-15214 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 14 to 17
2023-09-19 23:39:42.977 15171-15214 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 14 to 14
2023-09-19 23:39:42.979 15171-15214 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: upgrading database to 16
2023-09-19 23:39:42.979 15171-15214 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 15 to 17
2023-09-19 23:39:42.979 15171-15214 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: upgrading database to 17
2023-09-19 23:39:42.979 15171-15214 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 16 to 17
2023-09-19 23:39:42.979 15171-15214 sql_suppor...n_database com.igalia.wolvic.metastore          W  places: database operation failed: Error executing SQL: duplicate column name: unknown_fields
2023-09-19 23:39:42.979 15171-15214 error_support::handling com.igalia.wolvic.metastore          E  Error opening database: Error executing SQL: duplicate column name: unknown_fields
2023-09-19 23:39:42.980 15171-15214 PlacesBookmarksStorage  com.igalia.wolvic.metastore          W  Ignoring PlacesApiException while running getBookmarkWithUrl
                                                                                                    mozilla.appservices.places.uniffi.PlacesApiException$UnexpectedPlacesException: reason=Error opening database: Error executing SQL: duplicate column name: unknown_fields
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.read(places.kt:21)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.read(places.kt:1)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverter$DefaultImpls.liftFromRustBuffer(places.kt:13)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterRustBuffer$DefaultImpls.liftFromRustBuffer(places.kt:6)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.liftFromRustBuffer(places.kt:2)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.liftFromRustBuffer(places.kt:1)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterRustBuffer$DefaultImpls.lift(places.kt:7)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.lift(places.kt:3)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.lift(places.kt:2)
                                                                                                    	at mozilla.appservices.places.uniffi.PlacesApiException$ErrorHandler.lift(places.kt:2)
                                                                                                    	at mozilla.appservices.places.uniffi.PlacesApiException$ErrorHandler.lift(places.kt:1)
                                                                                                    	at mozilla.appservices.places.uniffi.PlacesKt.placesApiNew(places.kt:107)
                                                                                                    	at mozilla.appservices.places.PlacesApi.<init>(PlacesConnection.kt:9)
                                                                                                    	at mozilla.components.browser.storage.sync.RustPlacesConnection.init(Connection.kt:29)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:15)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesStorage.getPlaces$browser_storage_sync_release(PlacesStorage.kt:3)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesStorage$reader$2.invoke(PlacesStorage.kt:3)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesStorage.getReader$browser_storage_sync_release(PlacesStorage.kt:3)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$getBookmarksWithUrl$2.invokeSuspend(PlacesBookmarksStorage.kt:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:124)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
```

More backtraces of this kind. still during the app startup:

```
2023-09-19 23:39:43.607 15171-15506 PlacesHistoryStorage    com.igalia.wolvic.metastore          W  Ignoring PlacesApiException while running recordObservation
                                                                                                    mozilla.appservices.places.uniffi.PlacesApiException$UnexpectedPlacesException: reason=Error opening database: Error executing SQL: duplicate column name: unknown_fields
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.read(places.kt:21)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.read(places.kt:1)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverter$DefaultImpls.liftFromRustBuffer(places.kt:13)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterRustBuffer$DefaultImpls.liftFromRustBuffer(places.kt:6)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.liftFromRustBuffer(places.kt:2)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.liftFromRustBuffer(places.kt:1)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterRustBuffer$DefaultImpls.lift(places.kt:7)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.lift(places.kt:3)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.lift(places.kt:2)
                                                                                                    	at mozilla.appservices.places.uniffi.PlacesApiException$ErrorHandler.lift(places.kt:2)
                                                                                                    	at mozilla.appservices.places.uniffi.PlacesApiException$ErrorHandler.lift(places.kt:1)
                                                                                                    	at mozilla.appservices.places.uniffi.PlacesKt.placesApiNew(places.kt:107)
                                                                                                    	at mozilla.appservices.places.PlacesApi.<init>(PlacesConnection.kt:9)
                                                                                                    	at mozilla.components.browser.storage.sync.RustPlacesConnection.init(Connection.kt:29)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:15)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesStorage.getPlaces$browser_storage_sync_release(PlacesStorage.kt:3)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordObservation$2.invokeSuspend(PlacesHistoryStorage.kt:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:124)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)
```

When trying to access the saved logins, the following expcetion is raised:

```
2023-09-20 00:12:22.193 15171-15212 SecurePreferencesImpl23 com.igalia.wolvic.metastore          E  Decrypt exception: 
                                                                                                    javax.crypto.AEADBadTagException
                                                                                                    	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:611)
                                                                                                    	at javax.crypto.Cipher.doFinal(Cipher.java:2055)
                                                                                                    	at mozilla.components.lib.dataprotect.Keystore.decryptBytes(Keystore.kt:42)
                                                                                                    	at mozilla.components.lib.dataprotect.SecurePreferencesImpl23.getString(SecureAbove22Preferences.kt:64)
                                                                                                    	at mozilla.components.lib.dataprotect.SecureAbove22Preferences.getString(SecureAbove22Preferences.kt:8)
                                                                                                    	at mozilla.components.service.sync.logins.LoginsCrypto.getStoredKey(LoginsCrypto.kt:5)
                                                                                                    	at mozilla.components.concept.storage.KeyManager.getManagedKey(KeyManager.kt:5)
                                                                                                    	at mozilla.components.concept.storage.KeyManager.getOrGenerateKey$suspendImpl(KeyManager.kt:96)
                                                                                                    	at mozilla.components.concept.storage.KeyManager.getOrGenerateKey(KeyManager.kt:1)
                                                                                                    	at mozilla.components.service.sync.logins.SyncableLoginsStorage$list$2.invokeSuspend(SyncableLoginsStorage.kt:35)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:124)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
                                                                                                    Caused by: android.security.KeyStoreException: Signature/MAC verification failed
                                                                                                    	at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:356)
                                                                                                    	at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
                                                                                                    	at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:127)
                                                                                                    	at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
                                                                                                    	at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
                                                                                                    	at android.security.keystore2.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:396)
                                                                                                    	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:603)
                                                                                                    	at javax.crypto.Cipher.doFinal(Cipher.java:2055) 
                                                                                                    	at mozilla.components.lib.dataprotect.Keystore.decryptBytes(Keystore.kt:42) 
                                                                                                    	at mozilla.components.lib.dataprotect.SecurePreferencesImpl23.getString(SecureAbove22Preferences.kt:64) 
                                                                                                    	at mozilla.components.lib.dataprotect.SecureAbove22Preferences.getString(SecureAbove22Preferences.kt:8) 
                                                                                                    	at mozilla.components.service.sync.logins.LoginsCrypto.getStoredKey(LoginsCrypto.kt:5) 
                                                                                                    	at mozilla.components.concept.storage.KeyManager.getManagedKey(KeyManager.kt:5) 
                                                                                                    	at mozilla.components.concept.storage.KeyManager.getOrGenerateKey$suspendImpl(KeyManager.kt:96) 
                                                                                                    	at mozilla.components.concept.storage.KeyManager.getOrGenerateKey(KeyManager.kt:1) 
                                                                                                    	at mozilla.components.service.sync.logins.SyncableLoginsStorage$list$2.invokeSuspend(SyncableLoginsStorage.kt:35) 
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12) 
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:124) 
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4) 
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63) 
```

</details>

**Comment by javifernandez** [comment]
I tried the following test case in order to reproduce the issue:

1- clear all the Wolvic app data
2- Install 1.4.1 
3- Save some data (logins, bookmarks, history)
4. Upgrade to 1.4.2
5. Check that the data from 1.4.1 is correct
6. upgrade to 1.5 
7. Check that the data from 1.4.1 is correct

I couldn't reproduce the issue from 1.4.1, so the only plausible cause is some kind of corruption in the Wolvic storage folder, perhaps due to a bug in previous version of Wolvic;s shipping old version of the application-services (version < 74.0.1 )

I'll leve this bug open for now, but unconfirmed. It may be possible that some users report something similar after the upgrade to 1.5.

**Comment by javifernandez** [comment]
As discussed with @svillar we close these issues, and will reopen them if needed.
