### ISSUE TITLE
Can not save bookmarks

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#988]
## Configuration

Wolvic version: 1.5
Wolvic build ID:  112

Hardware: Oculus Quest2

## Steps to Reproduce

1. Load the  www.igalia.com  url
2. Click on the "star" icon to save the url in the Bookmarks folders
3.

## Current Behavior

The Bookmarks folder doesn't contain the www.igalia.com url

## Expected Behavior

The  www.igalia.com url should be stored in the Bookmarks folder

## Possible Solution

Deleting the App Data allows Wolvic 1.5 to save bookmarks.

## Error Logs and Stack Traces

<details open>

```
2023-09-20 00:24:59.658 15171-15287 places                  com.igalia.wolvic.metastore          D  places_cac2_places_api_new
2023-09-20 00:24:59.658 15171-15287 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: opening database
2023-09-20 00:24:59.659 15171-15287 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: checking if initialization is necessary
2023-09-20 00:24:59.663 15171-15287 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: preparing
2023-09-20 00:24:59.663 15171-15287 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: upgrading database to 14
2023-09-20 00:24:59.663 15171-15287 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 13 to 17
2023-09-20 00:24:59.663 15171-15287 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 13 to 13
2023-09-20 00:24:59.664 15171-15287 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: upgrading database to 15
2023-09-20 00:24:59.664 15171-15287 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 14 to 17
2023-09-20 00:24:59.664 15171-15287 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 14 to 14
2023-09-20 00:24:59.667 15171-15287 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: upgrading database to 16
2023-09-20 00:24:59.667 15171-15287 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 15 to 17
2023-09-20 00:24:59.667 15171-15287 sql_suppor...n_database com.igalia.wolvic.metastore          D  places: upgrading database to 17
2023-09-20 00:24:59.667 15171-15287 places::db::schema      com.igalia.wolvic.metastore          D  Upgrading schema from 16 to 17
2023-09-20 00:24:59.668 15171-15287 sql_suppor...n_database com.igalia.wolvic.metastore          W  places: database operation failed: Error executing SQL: duplicate column name: unknown_fields
2023-09-20 00:24:59.668 15171-15287 error_support::handling com.igalia.wolvic.metastore          E  Error opening database: Error executing SQL: duplicate column name: unknown_fields
2023-09-20 00:24:59.669 15171-15287 PlacesBookmarksStorage  com.igalia.wolvic.metastore          W  Ignoring PlacesApiException while running getBookmarkWithUrl
                                                                                                    mozilla.appservices.places.uniffi.PlacesApiException$UnexpectedPlacesException: reason=Error opening database: Error executing SQL: duplicate column name: unknown_fields
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.read(places.kt:21)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.read(places.kt:1)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverter$DefaultImpls.liftFromRustBuffer(places.kt:13)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterRustBuffer$DefaultImpls.liftFromRustBuffer(places.kt:6)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.liftFromRustBuffer(places.kt:2)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.liftFromRustBuffer(places.kt:1)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterRustBuffer$DefaultImpls.lift(places.kt:7)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.lift(places.kt:3)
                                                                                                    	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.lift(places.kt:2)
                                                                                                    	at mozilla.appservices.places.uniffi.PlacesApiException$ErrorHandler.lift(places.kt:2)
                                                                                                    	at mozilla.appservices.places.uniffi.PlacesApiException$ErrorHandler.lift(places.kt:1)
                                                                                                    	at mozilla.appservices.places.uniffi.PlacesKt.placesApiNew(places.kt:107)
                                                                                                    	at mozilla.appservices.places.PlacesApi.<init>(PlacesConnection.kt:9)
                                                                                                    	at mozilla.components.browser.storage.sync.RustPlacesConnection.init(Connection.kt:29)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:15)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesStorage.getPlaces$browser_storage_sync_release(PlacesStorage.kt:3)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesStorage$reader$2.invoke(PlacesStorage.kt:3)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesStorage.getReader$browser_storage_sync_release(PlacesStorage.kt:3)
                                                                                                    	at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$getBookmarksWithUrl$2.invokeSuspend(PlacesBookmarksStorage.kt:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:124)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)

```

</details>

**Comment by svillar** [comment]
OK so the precondition is that you should have a previous version of the DB. I understand bookmarking works fine in a fresh install right?

**Comment by javifernandez** [comment]
> OK so the precondition is that you should have a previous version of the DB. I understand bookmarking works fine in a fresh install right?

Correct. 

See my comment in #987 which probably has the same toot cause than this issue.

**Comment by javifernandez** [comment]
Closing it for now, as we are not able to reproduce it with a flesh install from 1.41 and upgrading to 1.5.
